### PR TITLE
simplify code contributions by fully automating the setup with gitpod.

### PR DESCRIPTION
**Pull request by nisarhassan12**
Hi! :slightly_smiling_face:

This Pr simplifies code contributions by fully automating the dev setup with gitpod(a free online VS Code like ide). With a single click it will launch a ready to code workspace where:

- uppload repo is already cloned.
- dependencies pre-installed.
- websevers via `npm run demo` and `npm run serve-site` running

so that anyone interested in contributing to the source code of the site can start away without wasting time on the dev setup.

You can give a try on my fork of the repo via the link below:

https://gitpod.io/#https://github.com/nisarhassan12/uppload

This is how it looks:

image

### CODE REVIEW

**Comment by AnandChowdhary** [comment]
Thanks for opening this PR. Can you share your relationship with GitPod, please? I want to make sure this is unambiguously non-promotional and better than options we’re currently using, like CodeSandbox.

**Comment by nisarhassan12** [comment]
Thanks! I work for them. We are on a mission to simplify open-source work by encouraging contributors to get started via automated dev environments. A lot of popular open-source projects are using Gitpod to simplify the experience for their contributors and maintainers. 


- https://github.com/facebook/docusaurus
- https://github.com/freeCodeCamp/freeCodeCamp
- https://github.com/carbon-app/carbon
- https://github.com/naptha/tesseract.js
- https://github.com/mozilla/pdf.js

You can find a detailed list on https://contribute.dev gitpod is not just a simple editor it's a full-featured IDE.

PRs can be reviewed from within Gitpod i.e you can comment/approve and so on.

**Comment by nisarhassan12** [comment]
Would you like to have the project listed on https://contribute.dev ?

**Comment by AnandChowdhary** [comment]
> Would you like to have the project listed on https://contribute.dev ?

Sure!

**Pull request merged**
